### ISSUE TITLE
use morph somehow?

### ISSUE THREAD

**Issue by silky** [mobeets/intriguing-things#1]
have you seen this? https://morph.io/

**Comment by silky** [comment]
(i'm thinking it might like you make the data available as a specific thing you could consume from elsewhere; and so could other people say.

but i don't really know what it is at all.)

**Comment by mobeets** [comment]
dammit, i knew i should have asked you if you knew a way of doing this! this seems really awesome, and i will definitely try it out next time i do something like this.

currently i'm struggling with getting this to be a heroku worker task that runs this once a day. but sadly, at this point i feel like i'm so close i might as well finish it off this way...

**Comment by silky** [comment]
oh yeah, it's totally worth knowing how to do it! worthwhile finishing.

i only suggested this because i saw the data updates on the repo and i was thinking "hmm, it would be nice to watch this repo but not see the notification of data changes, maybe the data could be hosted somewhere else...". but on the other hand, it might make sense to have the data here as well.

**Comment by mobeets** [comment]
yeah i liked the idea of having everything all in one place--then only the automation is separate.
but wooooo i love this morph thing. such a cool idea.

**Comment by mobeets** [comment]
alright, i'm using morph now. it was extremely easy! the only sad thing is that you need an api key to get the data--which i suppose makes sense. people seem to use their api key freely, though, so....whatever.
